const data = [
  {
    id: 1,
    image: '',
    titre: '7th Garden',
    nombreLu: '8',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 2,
    image: '',
    titre: 'Ash & Eli',
    nombreLu: '5',
    nombrePos: '',
    nombreTot: '6',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 3,
    image: '',
    titre: 'Black Torch',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '5',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 4,
    image: '',
    titre: 'Cage of Eden',
    nombreLu: '',
    nombrePos: '3',
    nombreTot: '21',
    fini: false,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 5,
    image: '',
    titre: 'Capitaine Albator - Dimension Voyage',
    nombreLu: '1',
    nombrePos: '4',
    nombreTot: '9',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 6,
    image: '',
    titre: 'Classroom for heroes',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 7,
    image: '',
    titre: 'Die & Retry',
    nombreLu: '5',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: '',
  },
  {
    id: 8,
    image: '',
    titre: 'Distopiary',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '5',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 9,
    image: '',
    titre: 'Drifters',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '6',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 10,
    image: '',
    titre: 'Egregor le souffle de la foi',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 11,
    image: '',
    titre: 'Fire Force',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '13',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 12,
    image: '',
    titre: 'Monster Hunter Epic',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '3',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 14,
    image: '',
    titre: 'My Hero Academia',
    nombreLu: '22',
    nombrePos: '24',
    nombreTot: '26',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 15,
    image: '',
    titre: 'Platinium End',
    nombreLu: '10',
    nombrePos: '12',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 16,
    image: '',
    titre: 'Red Dragon',
    nombreLu: '2',
    nombrePos: '5',
    nombreTot: '5',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 17,
    image: '',
    titre: 'Re:Zero – Troisième Arc - Truth of Zero',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '9',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 18,
    image: '',
    titre: 'Seraph of the End ()',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 19,
    image: '',
    titre: 'Twin star exorcists – Les Onmyôji Suprêmes',
    nombreLu: '18',
    nombrePos: '19',
    nombreTot: '21',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 20,
    image: '',
    titre: 'Why Nobody Remembers My World',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 21,
    image: '',
    titre: 'Witch Hunter',
    nombreLu: '22',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 22,
    image: '',
    titre: 'Negima !? Neo',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '7',
    fini: true,
    statut: 'Rech',
    maison: true,
  },
  {
    id: 23,
    image: '',
    titre: 'Bloody Monday',
    nombreLu: '9',
    nombrePos: '',
    nombreTot: '11',
    fini: true,
    statut: 'Rech',
    maison: true,
  },
  {
    id: 24,
    image: '',
    titre: 'L attaque des Titans',
    nombreLu: '',
    nombrePos: '6',
    nombreTot: '30',
    fini: false,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 25,
    image: '',
    titre: 'Gloutons & Dragons',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '7',
    fini: false,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 26,
    image: '',
    titre: 'Testament of Sister New Devil - storm',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '5',
    fini: false,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 27,
    image: '',
    titre: 'Vampire Doll',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '6',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 28,
    image: '',
    titre: 'Smokin Parade',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '7',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 29,
    image: '',
    titre: 'Ken en',
    nombreLu: '',
    nombrePos: '2',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 30,
    image: '',
    titre: 'Kaijin reijoh',
    nombreLu: '',
    nombrePos: '1',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 31,
    image: '',
    titre: 'Orient Samurai quest',
    nombreLu: '',
    nombrePos: '2',
    nombreTot: '',
    fini: false,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 32,
    image: '',
    titre: 'Arata',
    nombreLu: '23',
    nombrePos: '24',
    nombreTot: '25',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 33,
    image: '',
    titre: 'Blood & Steel',
    nombreLu: '8',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 34,
    image: '',
    titre: 'Bride Story',
    nombreLu: '11',
    nombrePos: '',
    nombreTot: '12',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 35,
    image: '',
    titre: 'Catacombes',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '4',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 36,
    image: '',
    titre: 'Final Fantasy - Lost Stranger',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '4',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 37,
    image: '',
    titre: 'Haikyu',
    nombreLu: '36',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 38,
    image: '',
    titre: 'Index (A Certain Magical Index)',
    nombreLu: '20',
    nombrePos: '22',
    nombreTot: '23',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 39,
    image: '',
    titre: 'Karneval',
    nombreLu: '11',
    nombrePos: '',
    nombreTot: '24',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 40,
    image: '',
    titre: 'Kuroko s Basket - extra game',
    nombreLu: '1',
    nombrePos: '2',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 42,
    image: '',
    titre: 'Magi - The Labyrinth of Magic',
    nombreLu: '35',
    nombrePos: '37',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: true,
  },
  {
    id: 41,
    image: '',
    titre: 'Mushoku Tensei',
    nombreLu: '6',
    nombrePos: '7',
    nombreTot: '10',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 43,
    image: '',
    titre: 'Pétales de Reincarnation',
    nombreLu: '7',
    nombrePos: '9',
    nombreTot: '10',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 44,
    image: '',
    titre: 'Radiant',
    nombreLu: '13',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 45,
    image: '',
    titre: 'Ragna Crimson',
    nombreLu: '5',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 46,
    image: '',
    titre: 'Sacred Beasts (To the Abandoned Sacred Beasts)',
    nombreLu: '5',
    nombrePos: '10',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 47,
    image: '',
    titre: 'TerraFormars',
    nombreLu: '4',
    nombrePos: '22',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 48,
    image: '',
    titre: 'TerraFormars - Rainhard',
    nombreLu: '',
    nombrePos: '1',
    nombreTot: '',
    fini: true,
    statut: 'AL',
    maison: false,
  },
  {
    id: 49,
    image: '',
    titre: 'The Rising of the Shield Hero',
    nombreLu: '13',
    nombrePos: '14',
    nombreTot: '15',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 50,
    image: '',
    titre: 'The Rising of the Shield Hero - Rathtalia',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 59,
    image: '',
    titre: 'Vinland Saga',
    nombreLu: '22',
    nombrePos: '23',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 60,
    image: '',
    titre: 'Xenoglossia',
    nombreLu: '',
    nombrePos: '2',
    nombreTot: '',
    fini: false,
    statut: 'AL',
    maison: false,
  },
  {
    id: 61,
    image: '',
    titre: 'Yureka',
    nombreLu: '34',
    nombrePos: '',
    nombreTot: '41',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 62,
    image: '',
    titre: 'Alderamin on the sky',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '7',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 63,
    image: '',
    titre: 'ARK:Romancer',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '3',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 64,
    image: '',
    titre: 'Code Geass - Shikkoku no Renya',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '7 (stop 5 FR)',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 65,
    image: '',
    titre: 'D.D.D.',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '3',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 66,
    image: '',
    titre: 'Dodoma',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '3',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 67,
    image: '',
    titre: 'Embalming - Une autre histoire de Frankenstein',
    nombreLu: '0',
    nombrePos: '3',
    nombreTot: '10',
    fini: true,
    statut: 'Inc',
    maison: '',
  },
  {
    id: 68,
    image: '',
    titre: 'Grimoire of Zero',
    nombreLu: '2',
    nombrePos: '4-6',
    nombreTot: '',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 69,
    image: '',
    titre: 'Im',
    nombreLu: '7',
    nombrePos: '',
    nombreTot: '11',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 70,
    image: '',
    titre: 'Kaitaishinsho Zero - Le livre des monstres',
    nombreLu: '7',
    nombrePos: '',
    nombreTot: '8',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 71,
    image: '',
    titre: 'Kingdom Hearts',
    nombreLu: '',
    nombrePos: '1',
    nombreTot: '4',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 72,
    image: '',
    titre: 'Monster Hunter Episodes',
    nombreLu: '',
    nombrePos: '2-3',
    nombreTot: '',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 73,
    image: '',
    titre: 'Nura le Seigneur des Yôkai',
    nombreLu: '17',
    nombrePos: '25',
    nombreTot: '',
    fini: true,
    statut: 'AL',
    maison: false,
  },
  {
    id: 74,
    image: '',
    titre: 'Red eyes sword - Akame ga Kill - Zero',
    nombreLu: '4',
    nombrePos: '9',
    nombreTot: '10',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 75,
    image: '',
    titre: 'Re:Zero Second Arc',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '5',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 76,
    image: '',
    titre: 'Reverend D',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '2',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 77,
    image: '',
    titre: 'Soul Eater',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '25',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 78,
    image: '',
    titre: 'Strike the Blood',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '10',
    fini: true,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 79,
    image: '',
    titre: 'Testament of Sister New Devil',
    nombreLu: '8',
    nombrePos: '9',
    nombreTot: '',
    fini: true,
    statut: 'AL',
    maison: false,
  },
  {
    id: 80,
    image: '',
    titre: 'The Qwaser of Stigmata',
    nombreLu: '4',
    nombrePos: '14',
    nombreTot: '',
    fini: true,
    statut: 'AL',
    maison: false,
  },
  {
    id: 81,
    image: '',
    titre: 'Undertaker Riddle',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '8',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 82,
    image: '',
    titre: 'Versus Earth',
    nombreLu: '',
    nombrePos: '4',
    nombreTot: '9',
    fini: true,
    statut: 'Inc',
    maison: false,
  },
  {
    id: 83,
    image: '',
    titre: 'Tsubasa RESERVoir CHRoNiCLE',
    nombreLu: '',
    nombrePos: '17',
    nombreTot: '28',
    fini: true,
    statut: 'Inc',
    maison: true,
  },
  {
    id: 84,
    image: '',
    titre: '',
    nombreLu: '',
    nombrePos: '5',
    nombreTot: '23',
    fini: true,
    statut: 'Inc',
    maison: true,
  },
  {
    id: 85,
    image: '',
    titre: 'All you need is Kill',
    nombreLu: '2',
    nombrePos: '2',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 86,
    image: '',
    titre: 'Astro boy',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 87,
    image: '',
    titre: 'Akaboshi',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 88,
    image: '',
    titre: 'Akatsuki',
    nombreLu: '9',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 89,
    image: '',
    titre: 'Antimagia',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 90,
    image: '',
    titre: 'Bestiarius',
    nombreLu: 'VII',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 91,
    image: '',
    titre: 'Black Bard',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 92,
    image: '',
    titre: 'Beach Stars',
    nombreLu: '7',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 93,
    image: '',
    titre: 'BB.Hell',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 94,
    image: '',
    titre: 'BeelZeBub',
    nombreLu: '(8)',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 95,
    image: '',
    titre: 'Bloody Cross',
    nombreLu: '11',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 96,
    image: '',
    titre: 'Buddy Spirits',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 97,
    image: '',
    titre: 'Chrome Breaker',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 98,
    image: '',
    titre: 'C(G)rimson-shell',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 99,
    image: '',
    titre: 'City Hall',
    nombreLu: '7',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 100,
    image: '',
    titre: 'Dark Air',
    nombreLu: '5',
    nombrePos: '',
    nombreTot: '8 (stop 5 fr)',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 101,
    image: '',
    titre: 'Di(e)ce',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 102,
    image: '',
    titre: 'Defense Devil',
    nombreLu: '10',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 103,
    image: '',
    titre: 'Devils and Realist',
    nombreLu: '7',
    nombrePos: '',
    nombreTot: '14 (stop 7 FR)',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 104,
    image: '',
    titre: 'Dimension W',
    nombreLu: '16',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 105,
    image: '',
    titre: 'Empress of Flamme',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 106,
    image: '',
    titre: 'Engage',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 107,
    image: '',
    titre: 'Gamaran',
    nombreLu: '22',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 108,
    image: '',
    titre: 'Grim Reaper',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 109,
    image: '',
    titre: '',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 110,
    image: '',
    titre: 'Kuroko s Basket',
    nombreLu: '30',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 111,
    image: '',
    titre: 'Kerberos in the Silver Rain',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 112,
    image: '',
    titre: 'Hades',
    nombreLu: '10',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 113,
    image: '',
    titre: "Hell's Kitchen",
    nombreLu: '13',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 114,
    image: '',
    titre: 'Hell Hell',
    nombreLu: '5',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 115,
    image: '',
    titre: 'Jusqu a ce que la mort nous separe',
    nombreLu: '26',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 116,
    image: '',
    titre: 'Les Six Destinees',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 117,
    image: '',
    titre: 'Letter Bee',
    nombreLu: '20',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 118,
    image: '',
    titre: 'Lords of chaos',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 119,
    image: '',
    titre: 'Lost Paradise',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 120,
    image: '',
    titre: 'Mawang le roi des demons',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '8 (stop 3 FR)',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 121,
    image: '',
    titre: 'MOMO the beautiful Spirit',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 122,
    image: '',
    titre: 'Monster hunter Flash',
    nombreLu: '10',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 123,
    image: '',
    titre: 'Pandora Hearts',
    nombreLu: '24',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 124,
    image: '',
    titre: 'Pochi & Kuro',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 125,
    image: '',
    titre: 'Psyren',
    nombreLu: '16',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 126,
    image: '',
    titre: 'Red eyes sword - Akame ga Kill',
    nombreLu: '15',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 127,
    image: '',
    titre: 'Re:Zero Premier Arc',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 128,
    image: '',
    titre: 'Samidare',
    nombreLu: '10',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 129,
    image: '',
    titre: 'Sai:Taker',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 130,
    image: '',
    titre: 'Superior',
    nombreLu: '9',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 131,
    image: '',
    titre: 'Superior cross',
    nombreLu: '6',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 132,
    image: '',
    titre: 'Taboo Tattoo',
    nombreLu: '13',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 133,
    image: '',
    titre: 'Trisagion',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 134,
    image: '',
    titre: 'The moon Sword',
    nombreLu: '5',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 135,
    image: '',
    titre: 'XBlade',
    nombreLu: '12',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 136,
    image: '',
    titre: 'XBlade cross',
    nombreLu: '8',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 137,
    image: '',
    titre: 'WarLord',
    nombreLu: '15',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 138,
    image: '',
    titre: 'Devil Devil',
    nombreLu: '15',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 139,
    image: '',
    titre: 'Monster Hunter Orage',
    nombreLu: '4',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 140,
    image: '',
    titre: 'Monster Soul',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 141,
    image: '',
    titre: 'Negima - Le maitre magicien',
    nombreLu: '38',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 142,
    image: '',
    titre: 'Mär',
    nombreLu: '15',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 143,
    image: '',
    titre: 'Ruroni Kenshin',
    nombreLu: '28',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 144,
    image: '',
    titre: 'Artelier',
    nombreLu: '13',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 145,
    image: '',
    titre: 'Pandora Hearts',
    nombreLu: '24',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: true,
  },
  {
    id: 146,
    image: '',
    titre: 'The Swordman',
    nombreLu: '9',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Fini',
    maison: false,
  },
  {
    id: 147,
    image: '',
    titre: '(template) avec Dernier numero',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '',
    fini: false,
    statut: 'Rech',
    maison: false,
  },
  {
    id: 2000,
    image: '',
    titre: 'Booksterz',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '3',
    fini: true,
    statut: 'Abandon',
    maison: false,
  },
  {
    id: 2001,
    image: '',
    titre: 'Imprimerie des sorcieres',
    nombreLu: '2',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Abandon',
    maison: false,
  },
  {
    id: 2002,
    image: '',
    titre: 'Food Wars',
    nombreLu: '1',
    nombrePos: '0',
    nombreTot: '',
    fini: true,
    statut: 'Abandon',
    maison: false,
  },
  {
    id: 2003,
    image: '',
    titre: 'Soul Reviver',
    nombreLu: '',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Abandon',
    maison: false,
  },
  {
    id: 2004,
    image: '',
    titre: 'La fille des enfers',
    nombreLu: '1',
    nombrePos: '',
    nombreTot: '',
    fini: true,
    statut: 'Abandon',
    maison: false,
  },
  {
    id: 2005,
    image: '',
    titre: 'Green worldz',
    nombreLu: '3',
    nombrePos: '',
    nombreTot: '8',
    fini: true,
    statut: 'Abandon',
    maison: true,
  },
  {
    id: 2006,
    image: '',
    titre: 'Knigths of sidonia',
    nombreLu: '2',
    nombrePos: '0',
    nombreTot: '',
    fini: true,
    statut: 'Abandon',
    maison: false,
  },
];

export default data;
